services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "9000:9000"
    # Diferente do dev:
    # 1. Não montamos volumes (o código é fixo na imagem)
    # 2. Política de reinício em caso de falha
    restart: always
    environment:
      - ENVIRONMENT=production
